spring:
  datasource:
#    url: jdbc:mysql://sh-cynosdbmysql-grp-ep3srdzu.sql.tencentcdb.com:26162/dcs?characterEncoding=utf8&useSSL=false
#    username: admin
#    password: admin@2021
    url: jdbc:mysql://10.125.11.167:3306/iheating_mis?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: password